# Generated by Django 3.1.5 on 2022-04-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
